
version: 0.2

env:
  variables:
    CI: "true"

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp build/ s3://jwilderspin-couk/ --recursive
